service: food-giver-user
package:
  exclude:
    - node_modules/aws-sdk/**

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: api
  timeout: 30
  tags:
    ms: food-giver-user
  logRetentionInDays: 7
  apiGateway:
    minimumCompressionSize: 102400 # Compress response when larger than specified size in bytes (must be between 0 and 10485760)

  # TODO: Configurar IAM

functions:
  customAuthorizer:
    # TODO: find a better way (not arn :/)
    handler: ../auth/src/v1/authorizer.run
    memorySize: 128
  healthCheck:
    handler: src/v1/health/check.run
    memorySize: 128
    events:
      - http:
          path: /user/health/check
          method: GET
  createUser:
    handler: src/v1/create.run
    memorySize: 128
    events:
      - http:
          path: /user
          method: POST
  checkExistentUser:
    handler: src/v1/checkExistentUser.run
    memorySize: 128
    events:
      - http:
          path: /user/{email}/check
          method: GET
  getUser:
    handler: src/v1/get.run
    memorySize: 128
    events:
      - http:
          path: /user/{email}
          method: GET
          authorizer: customAuthorizer

custom:
  serverless-offline:
    port: ${file(../../../dev.serverless.env.json):port.user}
  # Deletes all previous versions of the functions except for the last 'number' after deploy
  # Prevents the error: CodeStorageExceededException
  prune:
    automatic: true
    number: 3
  dotenv:
    path: ../../shared/.env
  webpack:
    excludeFiles: 
      - src/**/*.test.js
      - test/**/*.test.js

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin
