service: food-giver-donation
package:
  individually: true
  exclude:
    - node_modules/aws-sdk/**

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: api
  timeout: 30
  memorySize: 128
  tags:
    ms: food-giver-donation
  logRetentionInDays: 7
  apiGateway:
    minimumCompressionSize: 102400 # Compress response when larger than specified size in bytes (must be between 0 and 10485760)
  iamRoleStatements:
    ${file(../../shared/serverless-config.yml):iamRoleStatements}

functions:
  customAuthorizer:
    # TODO: find a better way (not arn :/)
    handler: src/v1/authorizer.run

  healthCheck:
    handler: src/v1/health/check.run
    events:
      - http:
          path: /donation/health/check
          method: GET
          cors: true

  createDonation:
    handler: src/v1/create.run
    events:
      - http:
          path: /donation/v1/users/{userEmail}/donations
          method: POST
          cors: true
          authorizer: customAuthorizer

  getDonations:
    handler: src/v1/list.run
    events:
      - http:
          path: /donation/v1/users/{userEmail}/donations
          method: GET
          cors: true
          authorizer: customAuthorizer
      - http:
          path: /donation/v1/donations
          method: GET
          cors: true
          authorizer: customAuthorizer

  getDonation:
    handler: src/v1/get.run
    events:
      - http:
          path: /donation/v1/users/{userEmail}/donations/{donationId}
          method: GET
          cors: true
          authorizer: customAuthorizer

  changeStatusDonation:
    handler: src/v1/changeStatus.run
    events:
      - http:
          path: /donation/v1/users/{userEmail}/donations/{donationId}/status
          method: PUT
          cors: true
          authorizer: customAuthorizer

custom:
  serverless-offline:
    lambdaPort: null
    httpPort: ${file(../../../dev.serverless.env.json):port.donation}
  # Deletes all previous versions of the functions except for the last 'number' after deploy
  # Prevents the error: CodeStorageExceededException
  prune:
    automatic: true
    number: 3
  dotenv:
    path: ../../shared/.env
  webpack:
    excludeFiles: 
      - src/**/*.test.js
      - test/**/*.test.js

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

