version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"

  - package_manager: "javascript"
    directory: "/app"
    update_schedule: "weekly"

  - package_manager: "javascript"
    directory: "/services"
    update_schedule: "weekly"

  - package_manager: "javascript"
    directory: "/services/modules/auth"
    update_schedule: "weekly"

  - package_manager: "javascript"
    directory: "/services/modules/donation"
    update_schedule: "weekly"

  - package_manager: "javascript"
    directory: "/services/modules/resources"
    update_schedule: "weekly"
  
  - package_manager: "javascript"
    directory: "/services/modules/user"
    update_schedule: "weekly"
