Resources:
  tableFGUser:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: FG.User
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  tableFGNecessity:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: FG.Necessity
      AttributeDefinitions:
        - AttributeName: userEmail
          AttributeType: S
        - AttributeName: necessityId
          AttributeType: S
      KeySchema:
        - AttributeName: userEmail
          KeyType: HASH
        - AttributeName: necessityId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  tableFGFood:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: FG.Food
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  tableFGDonation:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: FG.Donation
      AttributeDefinitions:
        - AttributeName: userEmail
          AttributeType: S
        - AttributeName: donationId
          AttributeType: S
      KeySchema:
        - AttributeName: userEmail
          KeyType: HASH
        - AttributeName: donationId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  tableFGChat:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: FG.Chat
      AttributeDefinitions:
        - AttributeName: chatId
          AttributeType: S
        - AttributeName: participant1
          AttributeType: S
        - AttributeName: participant2
          AttributeType: S
        - AttributeName: connectionId1
          AttributeType: S
        - AttributeName: connectionId2
          AttributeType: S
      KeySchema:
        - AttributeName: chatId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: participant1_index
          KeySchema:
          - AttributeName: participant1
            KeyType: HASH
          - AttributeName: participant2
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: connectionId1_index
          KeySchema:
          - AttributeName: connectionId1
            KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: connectionId2_index
          KeySchema:
          - AttributeName: connectionId2
            KeyType: HASH
          Projection:
            ProjectionType: ALL

  tableFGChatMessage:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: FG.ChatMessage
      AttributeDefinitions:
        - AttributeName: chatId
          AttributeType: S
        - AttributeName: messageId
          AttributeType: S
      KeySchema:
        - AttributeName: chatId
          KeyType: HASH
        - AttributeName: messageId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  
