service: food-giver-resources
package:
  exclude:
    - node_modules/aws-sdk/**

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: api
  timeout: 30
  tags:
    ms: food-giver-resources
  logRetentionInDays: 7
  apiGateway:
    minimumCompressionSize: 102400 # Compress response when larger than specified size in bytes (must be between 0 and 10485760)
  environment:
    apikey: l1o2c3a4l5k6e7y

  # TODO: Configurar IAM

functions:
  healthCheck:
    handler: src/v1/health/check.run
    memorySize: 128
    events:
      - http:
          path: /resources/health/check
          method: GET

custom:
  dynamodb:
    start:
      port: 8000
      migrate: true
      seed: false # deve ser true, quando existir arquivos de seed.
      convertEmptyValues: true
    stages:
      - api
    # Descomentar quando existir os arquivos de seed
    # seed:
    #   domain:
    #     sources:
    #       - table: FG.User
    #         sources: [./data/FG.User.json]
  serverless-offline:
    port: ${file(../../../dev.serverless.env.json):port.resources}
  # Deletes all previous versions of the functions except for the last 'number' after deploy
  # Prevents the error: CodeStorageExceededException
  prune:
    automatic: true
    number: 3
  webpack:
    excludeFiles: 
      - src/**/*.test.js
      - test/**/*.test.js

plugins:
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

resources:
  - ${file(./db.yml)}
