iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource:
      - arn:aws:dynamodb:*:*:table/FG.*
      - arn:aws:dynamodb:*:*:table/FG.*/index/*